title: M. Fatih's Blog
author: mfguney
email: mfguney@gmail.com
description: > 
  This blog share short notes for electronics and Embedded software.
theme: minima
linkedin_username: www.linkedin.com/in/mfguney
github_username:  https://github.com/mfguney 

show_excerpts: true
