title: M. Fatih's Blog
author: mfguney
email: mfguney@gmail.com
description: > 
  This blog share short notes for electronics and Embedded software.
theme: minima
linkedin_username: linkedin.com/in/m-fatih-güney-63399739
github_username:  https://github.com/mfguney 

show_excerpts: true
